create table public.resultados (
  id bigint generated by default as identity primary key,
  nombre text not null,
  grado text not null,
  mision text not null,
  nota numeric(2,1) not null,
  aciertos integer not null,
  total integer not null,
  puntaje integer not null,
  mejor_racha integer not null,
  fecha timestamptz not null
);

alter table public.resultados enable row level security;

create policy "permitir insertar resultados"
  on public.resultados
  for insert
  to anon
  with check (true);

create policy "permitir consultar resultados"
  on public.resultados
  for select
  to authenticated
  using (true);
